### ISSUE TITLE
Even with #pragma rtl, exit() still calls a GS/OS Quit call.

### ISSUE THREAD

**Issue by sheumann** [byteworksinc/ORCALib#19]
Even with #pragma rtl, exit() still calls a GS/OS Quit call.
[libca13.c], sh

**Comment by sheumann** [comment]
libca13.c:

```
/*
 * Bug in ORCA/C 2.1
 * Run-time
 *
 * Even with the rtl pragma, and I noticed that the exit()
 * function appears to do a QuitGS instead of an RTL in this case.
 * Not good. :)
 * (Sheppy)
 */

#pragma rtl

#include <stdlib.h>

int main (void)
{
  exit (0); // Check object code to see whether this does an RTL or not
}
```

**Comment by ksherlock** [comment]
Could make use of soft references to check for the ~RTL symbol which would indicate at least one file was linked with #pragma rtl....

https://github.com/byteworksinc/ORCALib/blob/7abdfc9beb34966fecfe34d50c98ff5eddbd0bb2/stdlib.asm#L315-L318

	_exit	entry
		lda 4,s
	*	ldx #W:~RTL
		dc i1'$a2' 
		dc s2'~RTL'
		beq quit
		dex
		phx
		rts
	quit	anop
		jmp ~QUIT
		end
