### ISSUE TITLE
va_end() crashes the system

### ISSUE THREAD

**Issue by sduensin** [byteworksinc/ORCALib#30]
Test code attached.

[testSomething.c.txt](https://github.com/byteworksinc/ORCALib/files/2325992/testSomething.c.txt)

**Comment by sheumann** [comment]
By default, ORCA/C generates stack repair code that is incompatible with the `va_start`/`va_end` macros. As mentioned in the manual, you need to disable stack repair code in any functions using those macros. You can do that by using

```
#pragma optimize 8 /* or a higher value that includes bit 3 set */
```

Note that these facilities in ORCA/C are not quite standard-compliant in a couple other ways as well, although typical use cases will generally work. These include that you can’t restart variable argument processing by calling `va_start` after `va_end`, and that the addresses of local variables will change when `va_end` is called. Also see the discussion in the release notes about `#pragma optimize` bit 6 and its effect on variable argument function calls. (These issues all stem from the fact that `va_end` will actually remove the variable arguments from the stack.)

**Comment by sduensin** [comment]
I have read that manual for weeks straight and totally missed that part about va_args.   Thank you!  Correcting my brain fixed my issue.  :-)

Amazing response time, too!
