### ISSUE TITLE
sane.h  / SANEStartUp

### ISSUE THREAD

**Issue by ksherlock** [byteworksinc/ORCALib#31]
`extern pascal void SANEStartUp() inline(0x020A,dispatcher);`

needs a direct page parameter:

`extern pascal void SANEStartUp(Word) inline(0x020A,dispatcher);`

**Comment by sheumann** [comment]
Addressed via commit byteworksinc/ORCA-C@1af7505a00cb93ef7de6b144bd74fe94173d43de.
